install.packages("ggplot2")   
install.packages("randomForest")   
install.packages("MASS")
install.packages("tigerstats")
install.packages("party")
install.packages("lattice")
install.packages("scatterplot3d")